### ISSUE TITLE
Can't see problems of assets

### ISSUE THREAD

**Issue by cptalpdeniz** [bloodypenguin/Skylines-ModTools#11]
As the title says, can't see the asset problem info text due to ModTools info text of the asset. For example, when there is no road connection a road connection icon pops-up to tell the player that the asset requires a road connection. If player doesn't know what that icon means, he/she can see it by clicking on the asset. Is it possible to see both at the information windows?

**Comment by bloodypenguin** [comment]
The only thing I can do about it is to replace the editable name of building etc. with asset name. Will that work for you? But there's no real need in that because you can show/hide UI extensions through ModTools options panel.

**Comment by dymanoid** [comment]
This is fixed with 26214166b29551c741431b4c797185eecb53b0bb.
