### ISSUE TITLE
Keyboard command with backquote incorrect

### ISSUE THREAD

**Issue by RileyBaird** [bloodypenguin/Skylines-ModTools#16]
https://github.com/bloodypenguin/Skylines-ModTools/blob/237a2d3f249dcdaa897d4bd9bbaf64f35455e864/Debugger/ModTools.cs#L222

Line 222 in ModTools.cs reads `if (Input.GetKeyDown(KeyCode.BackQuote))`, however, Line 349 indicates the keyboard shortcut to be Control-Backquote.

Line 222 should maybe be updated to read `if (Input.GetKey(KeyCode.LeftControl) && Input.GetKeyDown(KeyCode.BackQuote))`.

(Note: this is relevant to me because holding the backquote key allows me to move my camera!)

**Comment by dymanoid** [comment]
This is fixed with 26214166b29551c741431b4c797185eecb53b0bb.
The shortcut has been changed to `Ctrl + S` (for *scripting*).
