### ISSUE TITLE
"Find in scene explorer" button not showing up

### ISSUE THREAD

**Issue by boformer** [bloodypenguin/Skylines-ModTools#2]

**Comment by Katalyst6** [comment]
Object.Instantiate is totally killing the CPU...
Line 38 of CSL.NetworkExtensions/Framework/ToolsCSL.cs

**Comment by boformer** [comment]
I also think that the dump mesh + texture button was more useful than the preview button.

**Comment by bloodypenguin** [comment]
Looks like getName call during the game resets the mod so that panel extensions disappear. Again, that happens when mods with 'Options' button are active
