### ISSUE TITLE
Cannot dump assets that use a custom window

### ISSUE THREAD

**Issue by TBleader** [bloodypenguin/Skylines-ModTools#22]
Certain assets such as the Chirpx Rocket Launchpad and all the new specialized industry buildings use a custom window in game. The Dump button does not appear on any of these windows. I would assume the code to add that button is specific to the type of window that most buildings share, but since these do not then that button doesn't show up. It would be nice to be able to dump these assets, a lot of very nice buildings have been added as a part of the new Industries DLC.

**Comment by TBleader** [comment]
@bloodypenguin figured I would ask if you've taken a look. Additionally, dump assets fails to dump some parts of buildings. International Airport only dumps the center bit. Ocean Thermal Plant only dumps the shore part, not the part in the ocean. It's easy to tell when this will happen by viewing the model in the scene browser, it is an incomplete model. My guess is that some buildings have multiple separate models that are loaded in, not sure of a way to export those.

**Comment by dymanoid** [comment]
The missing buttons were added in 26214166b29551c741431b4c797185eecb53b0bb.
