### ISSUE TITLE
ModTools doesn't seem to work in 1.13

### ISSUE THREAD

**Issue by Rekov3D** [bloodypenguin/Skylines-ModTools#28]
Unfortunately I'm not the best person to make this report, as I only subscribed to ModTools after the Sunset Harbor patch. It doesn't seem to be working though. The 'Dump asset' button doesn't appear, nor do the menu or screen explorer. I could be wrong though, as I've never used the working version.

**Comment by dymanoid** [comment]
Cannot reproduce that. Can you provide a screenshot?

**Comment by Rekov3D** [comment]
My mistake. I looked in my steamapps/workshop/content folder and discovered that the mod wasn't actually downloading for some reason while other mods were. Anyways, I was able to solve this problem on my end.
