### ISSUE TITLE
idea: Copy and paste any C# object.

### ISSUE THREAD

**Issue by boformer** [bloodypenguin/Skylines-ModTools#4]
Right now it is hard to change fields which are not primitive types or enums, for example a texture.

It would be great if you could add a copy and paste function.

All that is needed are 2 additional buttons right next to the Watch button. One to copy any object reference, one to paste the clipboard value to the field.

**Comment by bloodypenguin** [comment]
Implemented in 3cba2f3e89928a832a8dff575d33e2a579dd1990
