### ISSUE TITLE
Collection index selection not working correcly

### ISSUE THREAD

**Issue by boformer** [bloodypenguin/Skylines-ModTools#6]
It is not possible to change the "Start Index" or "End Index" (throws error). You can only see the first 32 items of any collection.

**Comment by bloodypenguin** [comment]
That's exactly what I'm working on right now - on simplifying navigation through collections. But I could change start and end indices even prior to that. Can you provide me with steps to reproduce the exception?

**Comment by boformer** [comment]
What I found out so far is that it only happens when you press ENTER after changing the number.

So it is possible to change start and end index, you just have to click somewhere else in the window instead of pressing ENTER.

Not at my pc right now, so no exception...

**Comment by bloodypenguin** [comment]
Got it. Have never used ENTER :)

**Comment by dymanoid** [comment]
This is fixed with 26214166b29551c741431b4c797185eecb53b0bb.
